### ISSUE TITLE
Перекрасить цену под кнопкой покупки билета в хэдере

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#29]
<img width="264" alt="screen shot 2018-04-06 at 15 37 30" src="https://user-images.githubusercontent.com/14319530/38422472-8b9dd764-39b3-11e8-9878-7f40310b2c12.png">

Хочется нажать на цену (я постоянно в неё тычу), а она не ссылка :С

**Comment by tsergeytovarov** [comment]
Привет.

**Comment by tsergeytovarov** [comment]
Лёша предлагает чёрный

**Comment by tsergeytovarov** [comment]
<img width="245" alt="screen shot 2018-04-07 at 14 31 26" src="https://user-images.githubusercontent.com/3905611/38454019-6430ba12-3a70-11e8-9a48-46327ff1536b.png">

**Comment by tsergeytovarov** [comment]
вот так, оставляем?

**Comment by thatsnotplasticine** [comment]
Может, так?
<img width="249" alt="screen shot 2018-04-07 at 13 29 29" src="https://user-images.githubusercontent.com/14319530/38454063-92aa982a-3a68-11e8-9d94-69ff36edb8df.png">

#4f3b98


Хотя в чёрный тоже норм -__-
