### ISSUE TITLE
Уменьшить отступы после списка докладов

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#30]
_Ту мач фри спэйс._
<img width="1376" alt="screen shot 2018-04-06 at 14 30 47" src="https://user-images.githubusercontent.com/14319530/38422551-d6741938-39b3-11e8-89a2-16e421d6d60b.png">

Надо убрать такие конские отступы у блока.

**Comment by tsergeytovarov** [comment]
уже убраны
