### ISSUE TITLE
Выровнять текст на странице CoC

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#31]
<img width="333" alt="screen shot 2018-04-06 at 15 29 00" src="https://user-images.githubusercontent.com/14319530/38422612-1c324986-39b4-11e8-83b9-fe87eda30e50.png">
<img width="303" alt="screen shot 2018-04-06 at 15 29 09" src="https://user-images.githubusercontent.com/14319530/38422613-1c509a94-39b4-11e8-9716-a3211aed08ac.png">

**Comment by tsergeytovarov** [comment]
вообще это шрифт, но я подвинул ссылку чуть правее
