### ISSUE TITLE
Поправить отступы у заголовков на странице

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#32]
<img width="947" alt="screen shot 2018-04-06 at 15 35 04" src="https://user-images.githubusercontent.com/14319530/38422672-4d373a14-39b4-11e8-9743-a881cd27b729.png">

Поправить отступы у заголовков на странице. После параграфа (до заголовка) — отступ больше. После заголовка и до параграфа — меньше. А то каша.

**Comment by tsergeytovarov** [comment]
готово
