### ISSUE TITLE
Вытащить текст из-под паттерна на главной странице (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#33]
![img_9927](https://user-images.githubusercontent.com/14319530/38422939-2153bfde-39b5-11e8-84c4-57e804fdacb2.jpg)

Паттерн залезает на текст.
(Chrome 65.0.3325.152, iPhone SE)

**Comment by tsergeytovarov** [comment]
теперь он над паттерном
