### ISSUE TITLE
Сворачивать и разворачивать докладчика по тапу (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#34]
![img_9928](https://user-images.githubusercontent.com/14319530/38423031-69299266-39b5-11e8-98b1-4d27cb615d13.PNG)

Хочется сворачивать и разворачивать по тапу на имя и тему доклада, а не только на +

**Comment by tsergeytovarov** [comment]
сворачивается и разворачивается при клике на весь блок теперь
