### ISSUE TITLE
Сделать простым текстом фразу Will be anounced в расписании докладов (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#35]
Will be anounced почему-то интерактивный элемент. Сделать его обычным текстом.

![img_9929](https://user-images.githubusercontent.com/14319530/38423107-9fca53be-39b5-11e8-93b1-042b01998e8e.PNG)

**Comment by tsergeytovarov** [comment]
не только на мобильном кстати. УБрал

**Comment by thatsnotplasticine** [comment]
На десктопе до сих пор (**даже после кмд шифт р**) Will be anounced нажимается и разворачивает пустоту.

**Comment by thatsnotplasticine** [comment]
@tsergeytovarov как дела?
