### ISSUE TITLE
Добавить видео или убрать его из заголовка (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#36]
![img_9930](https://user-images.githubusercontent.com/14319530/38423229-fb99fd16-39b5-11e8-9caa-b416740aa628.PNG)

Про видео пишем, а его нет. Только фотки.

**Comment by tsergeytovarov** [comment]
Видео было, просто слайд назад, но оно жёстко ломало галерею, поэтому я её частично переделил. Видео теперь первое.
