### ISSUE TITLE
Оферта и CoC не выглядят, как ссылки (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#37]
![img_9931](https://user-images.githubusercontent.com/14319530/38423268-1b7b2560-39b6-11e8-93f2-606d39544a44.PNG)

Сделать их ссылками — пунктирное подчёркивание как на десктопе?

**Comment by thatsnotplasticine** [comment]
Не нашла пунктирное подчёркивание на десктопе, но где-то я его точно видела.

**Comment by tsergeytovarov** [comment]
оно теперь не пунктирное, а просто, подчеркивание и я увеличил контрастность!
