### ISSUE TITLE
Поле ввода почты и кнопка немного поехали (мобильная версия)

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#38]
![img_9932](https://user-images.githubusercontent.com/14319530/38423346-4c6aa59c-39b6-11e8-8020-e1a2021363de.PNG)

Я не знаю, что можно с этим сделать, но выглядит странно.

**Comment by pepelsbey** [comment]
Предлагаю всем кнопкам сделать `white-space: nowrap` и писать в них всё короче

**Comment by tsergeytovarov** [comment]
поправил
