### ISSUE TITLE
Высота карты относительно высоты окна

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#41]
<img width="1144" alt="screen shot 2018-04-06 at 18 00 22" src="https://user-images.githubusercontent.com/14319530/38428482-7fd77d84-39c4-11e8-989d-544453948d4d.png">

Это не круто. Она там на процентах?
Что с этим можно сделать? Фиксированную высоту?

**Comment by tsergeytovarov** [comment]
поставил минимальную высоту 500 пикселей, чтобы меньше не ужималась
