### ISSUE TITLE
Выравнивание Buy tickets в кнопке в хэдере

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#42]
<img width="256" alt="screen shot 2018-04-07 at 14 39 30" src="https://user-images.githubusercontent.com/14319530/38454515-a3a436c8-3a71-11e8-8b79-1a8dbc232536.png">

Текст уехал куда-то вверх.

**Comment by thatsnotplasticine** [comment]
<img width="256" alt="screen shot 2018-04-07 at 14 39 30 copy" src="https://user-images.githubusercontent.com/14319530/38454599-bfea3976-3a72-11e8-8b13-a4355acb346b.png">

А может там ещё и подпись под кнопкой выровнять?

**Comment by tsergeytovarov** [comment]
поправил обе
