### ISSUE TITLE
Переименовать leader в host

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/2018#46]
Блок `leader` с головой на главной.

**Comment by tsergeytovarov** [comment]
видимо это сделано

**Comment by pepelsbey** [comment]
Нет, я имел в виду не файлы с картинкой, я имел в виду название блока и все имена классов.

**Comment by tsergeytovarov** [comment]
я думал речь вообще про надпись в блоке. Это не мешает стартануть короче

**Comment by pepelsbey** [comment]
Не все баги, которые я ставлю, мешают стартануть. Тот же `announced`, но ты его исправил )
