### ISSUE TITLE
Переключать лейбл на кнопке

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/2018#47]
Раньше всегда было `aria-label="Open talk description"` вне зависимости от открытости описания. Нужно тоглить лейбл на `Close talk description`, причём строку лучше хранить в data-атрибуте прямо в HTML, а не в JS.

Я пока исправил на `Toggle talk description`, но это костыль:
```
<button class="session__toggle session__toggle--hide" type="button" aria-label="Toggle talk description"></button>
```

**Comment by tsergeytovarov** [comment]
я бы оставил просто Toggle talk description или переписал это когда доделаем рапсиание
