### ISSUE TITLE
Обрабатывать закрытие только по кнопке

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/2018#48]
Сейчас доклад в программе в закрытом состоянии имеет ховер и кликабелен, как и кнопка. Но если открыть доклад, то никакого ховера нет, но доклад отстаётся (внезапно) кликабельным. Лучше, чтобы для закрытия работала только кнопка, без сюрпризов.

**Comment by tsergeytovarov** [comment]
Это когда кнопки будут

**Comment by neesoglasnaja** [comment]
@pepelsbey @tsergeytovarov А у вас специально на сайте в закрытом виде крестики/кнопочки с докладами имеют обратную логику? Я долго пыталась понять, что значит крестик рядом со спикером. Идеи были в стиле "мне не нравится доклад" и "убрать его из своей программы"

**Comment by pepelsbey** [comment]
@neesoglasnaja fixed! Спасибо :)

**Comment by pepelsbey** [comment]
@tsergeytovarov, повышаю до критикал — ссылки не работают. Закрывать нужно только по кнопке.
