### ISSUE TITLE
Выползает странный фон по мере добавления контента

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#49]
Кажется, так не должно быть. Это можно поправить?

<img width="957" alt="screen shot 2018-04-08 at 18 51 50" src="https://user-images.githubusercontent.com/14319530/38469612-447e3000-3b60-11e8-82eb-336ccc82bdbc.png">

<img width="458" alt="screen shot 2018-04-08 at 18 56 30" src="https://user-images.githubusercontent.com/14319530/38469613-44ba8230-3b60-11e8-9aba-e264f3f4e9c3.png">

**Comment by tsergeytovarov** [comment]
готово, я его спрятал, от контента будем менять размер в секии заднего фона
