### ISSUE TITLE
Добавить фотографии оргов и информацию про нас на CFS

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#51]
<img width="942" alt="screen shot 2018-04-09 at 11 44 23" src="https://user-images.githubusercontent.com/14319530/38488284-aec10f74-3beb-11e8-918e-62c7bcdd91d4.png">

Фотографии в гуглдрайве.

**Comment by tsergeytovarov** [comment]
оставил пулл реквест на @pepelsbey
