### ISSUE TITLE
Поправить текст 14 more to come…, потому что все думают, что это ссылка

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#52]
...которая ведёт на список из 14 докладчиков. Три независимых тестировщика сказали одно и то же.

<img width="347" alt="screen shot 2018-04-09 at 12 04 52" src="https://user-images.githubusercontent.com/14319530/38489231-697bab4c-3bee-11e8-86e3-786f60be241e.png">

**Comment by thatsnotplasticine** [comment]
@pepelsbey ты за тексты?

**Comment by pepelsbey** [comment]
Поправить в каком смысле? Там по-английски написано «будут ещё 14», как мне это поправить?

**Comment by thatsnotplasticine** [comment]
Я не знаю. Я говорю то, что говорят мне. 
Может, стоит написать это другим размером шрифта? Чтобы он отличался от имени и заголовка докладов? Меньше? Бледнее?

<img width="259" alt="screen shot 2018-04-09 at 12 31 02" src="https://user-images.githubusercontent.com/14319530/38490490-e6a9eb76-3bf1-11e8-8f4e-435716b07563.png">
