### ISSUE TITLE
Странные символы на первом экране

### ISSUE THREAD

**Issue by neesoglasnaja** [pitercss/2018#53]
Windows 10, Chrome 65.0.3325.181

Видимые непечатные символы в хедере и на главном слайде http://prntscr.com/j36xoi

**Comment by tsergeytovarov** [comment]
@neesoglasnaja привет! Видим, вроде убрали. Проверишь у себя?

**Comment by neesoglasnaja** [comment]
У меня все окей теперь :)

**Comment by tsergeytovarov** [comment]
Спасибо!
