### ISSUE TITLE
Добавить ссылку на альбом на фейсбуке на главную страницу

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#54]
[Ссылка на фейсбучный альбом](https://www.facebook.com/media/set/?set=a.453600831685091.1073741829.382592345452607&type=1&l=db2c208621)

Центрированный текст после последней фотографии.

**Comment by thatsnotplasticine** [comment]
@pepelsbey дай текст для ссылки.

**Comment by pepelsbey** [comment]
Текст ссылки ровно такой, как был, когда его затёрли новым дизайном.

**Comment by pepelsbey** [comment]
Спасибо, @tsergeytovarov :)
