### ISSUE TITLE
Добавить рамку под шапкой

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/2018#55]
У нас она есть там, где не нужно:

![image](https://user-images.githubusercontent.com/105274/38555239-1b1944ce-3cce-11e8-8484-9f6147b746bf.png)

И нет, там, где нужно:

![image](https://user-images.githubusercontent.com/105274/38555251-28b44976-3cce-11e8-9015-44fc692cd1f7.png)

Суть этой рамки: одна должна быть на шапке (или контентном блоке) и выставляться классом. Там, где страница под шапкой белая — рамка нужна. Там, где цветная — не нужна.

**Comment by pepelsbey** [comment]
На главной всё ещё есть рамка

![image](https://user-images.githubusercontent.com/105274/38888009-0d5d7aca-4283-11e8-8c2a-c7e18598e131.png)

**Comment by pepelsbey** [comment]
![image](https://user-images.githubusercontent.com/105274/39912232-c1e60c4c-5506-11e8-9f67-6e0463293e03.png)

Рамки снова нет. Или по-прежнему?

**Comment by tsergeytovarov** [comment]
Да это из-за `overflow`, надо короче делать шапку по другому, добавлять внешнюю доп обёртку. Это потребует какое-то время

**Comment by pepelsbey** [comment]
Проверил, `border-bottom` срабатывает:

![image](https://user-images.githubusercontent.com/105274/39918648-d1600750-5519-11e8-8dbb-67a8d5773cb6.png)

Что я делаю не так?

**Comment by pepelsbey** [comment]
Нужен просто модификатор `header--border` с нижней рамкой, который вставлять там, где нужно. Или наоборот убирать на главной, что кажется логичнее.

**Comment by pepelsbey** [comment]
@tsergeytovarov мы успеем добавить рамку до конференции? Два месяца уже прошло (

![image](https://user-images.githubusercontent.com/105274/40724848-b9606616-642a-11e8-8e84-52592d5578f8.png)
