### ISSUE TITLE
Двойное подчёркивание у промокода

### ISSUE THREAD

**Issue by meritt** [pitercss/2018#58]
В Сафари у поле промокода не всё хорошо.

<img width="801" alt="screen shot 2018-04-10 at 15 40 18" src="https://user-images.githubusercontent.com/10909/38557635-4e76dff4-3cd6-11e8-86f3-e62fb483aa4f.png">

А вот так выглядят обычные поля

<img width="595" alt="screen shot 2018-04-10 at 15 39 56" src="https://user-images.githubusercontent.com/10909/38557675-652af442-3cd6-11e8-80bd-ddfc82559b70.png">

**Comment by tsergeytovarov** [comment]
напиши, что конкретно не так с обычными полями.

**Comment by meritt** [comment]
С обычными всё хорошо. Не хорошо с промокодом.

**Comment by tsergeytovarov** [comment]
сейчас вроде всё хорошо.
