### ISSUE TITLE
Переполнение эмоджами бейджа

### ISSUE THREAD

**Issue by meritt** [pitercss/2018#59]
Не знаю что с этим делать, просто картинка на обсуждение.

<img width="1066" alt="screen shot 2018-04-10 at 15 54 17" src="https://user-images.githubusercontent.com/10909/38557994-7b0b5cce-3cd7-11e8-8ebd-2ba9a3acbfa2.png">

/cc @pepelsbey @thatsnotplasticine

**Comment by tsergeytovarov** [comment]
Наркоманы

**Comment by pepelsbey** [comment]
Нужно сделать `white-space: nowrap` для вывода всех полей. И скрывать переполнение. Ну и ограничить длину полей с помощью `maxlenght`?

**Comment by tsergeytovarov** [comment]
так и сделал

**Comment by pepelsbey** [comment]
Что-то `maxlength="15"` не работает: `1234567890123456789012`.

![image](https://user-images.githubusercontent.com/105274/38872560-3e873680-425c-11e8-9986-60832ec79941.png)

**Comment by pepelsbey** [comment]
В `maxlength="15"` не влезает фамилия Константинопольский. Бывают двойные фамилии, вроде Муравьёв-Апостол или что-то вроде. Я бы подумал чуть более внимательно, как реализовать это. Скажем, убрать `white-space: nowrap`, но добавить `maxlength` побольше и потестировать на переполнение контентом, как учат в Академии.

![image](https://user-images.githubusercontent.com/105274/38888371-19f0414a-4284-11e8-818e-df0f33ac9727.png)

**Comment by tsergeytovarov** [comment]
сейчас стоит везде ограничение по 20 и стоит white-space: nowrap
