### ISSUE TITLE
Добавить на страницу for-companies-ru пункт про количество дней

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#61]
<img width="877" alt="screen shot 2018-04-11 at 15 46 50" src="https://user-images.githubusercontent.com/14319530/38617398-978574ac-3d9f-11e8-93ff-13a38c4c9f32.png">

Чтобы сразу писали, какой билет хотят купить.

**Comment by pepelsbey** [comment]
Fixed
