### ISSUE TITLE
Поправить ссылку на Серёжин твиттер :О

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#64]
<img width="330" alt="screen shot 2018-04-24 at 18 43 45" src="https://user-images.githubusercontent.com/14319530/39198349-86e08a1a-47ef-11e8-946e-84257f819c3b.png">

[https://twitter.com/sergeytovarov](url) :О
А то там сейчас Лёша скрывается.

**Comment by thatsnotplasticine** [comment]
Ой. [Вот тут.](https://pitercss.com/code-of-conduct)

**Comment by pepelsbey** [comment]
Поправил и задеплоил
