### ISSUE TITLE
Горизонтальный скролл на сайте

### ISSUE THREAD

**Issue by MeFoDy** [pitercss/2018#66]
В Chrome и Firefox (Windows):

![pitercss_conf june 8 9th 2018 - google chrome 2018-04-26 19 15 10](https://user-images.githubusercontent.com/1439919/39318412-bbe39e58-4986-11e8-9706-96035eb18d7b.png)
![pitercss_conf june 8 9th 2018 - google chrome 2018-04-26 19 15 47](https://user-images.githubusercontent.com/1439919/39318414-bc193a90-4986-11e8-9f62-dcde95a8dbdb.png)

В Edge:

![microsoft edge 2018-04-26 19 18 41](https://user-images.githubusercontent.com/1439919/39318438-c9f70192-4986-11e8-961d-ee02d37e6ffa.png)

Есть подозрение, что проблема где-то [здесь](https://github.com/pitercss/2018/commit/23dc84c2358a70d156ae925e076ee0a351fe748f#diff-16a67b3987ad197ffa69a58b16e276ecR13).

**Comment by tsergeytovarov** [comment]
спасибо, поправили.
