### ISSUE TITLE
На мобильной версии сайта нет адреса площадки

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#67]
Alarm!
@pepelsbey @tsergeytovarov

**Comment by pepelsbey** [comment]
Предлагаю на мобильной версии адаптировать так, чтоы адрес было видно, скажем, параграфом под этим. Иначе это пока единственное место, где написано куда ехать.

![image](https://user-images.githubusercontent.com/105274/39373098-2b228e1e-4a4f-11e8-84b4-f168f5389916.png)
