### ISSUE TITLE
Страница с географией участников

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#69]

**Comment by thatsnotplasticine** [comment]
[Ой.](https://docs.google.com/document/d/1NovKPI5FS9UnFtdhAyTGCraw3mKZlupjTCjR6DWT2Us/edit?usp=sharing)
@tsergeytovarov вон там.

**Comment by tsergeytovarov** [comment]
я сделал /members 
мне не нравится как выглядит, надо вступительный абзац.

**Comment by tsergeytovarov** [comment]
пока не закрываю

**Comment by tsergeytovarov** [comment]
Тут так и не понятно, страница есть, там добавлено, но на неё не ведёт ничего и на неё не понятно как попасть и она плохо выглядит. Возможно если список заменить на карту то будет лучше.
