### ISSUE TITLE
Поправить текст на странице с картой

### ISSUE THREAD

**Issue by thatsnotplasticine** [pitercss/2018#70]
@pepelsbey как думаешь?
Может заголовки у этих блоков поправить на **some interesting events before** и **and after**?

<img width="905" alt="screen shot 2018-05-01 at 15 52 43" src="https://user-images.githubusercontent.com/14319530/39473543-00683050-4d58-11e8-8cd9-bb6bd24f670e.png">

**Comment by thatsnotplasticine** [comment]
Вот так, короче.

<img width="907" alt="screen shot 2018-05-01 at 15 58 06" src="https://user-images.githubusercontent.com/14319530/39473637-7b518b54-4d58-11e8-9a5d-b21b1b5de49e.png">

**Comment by pepelsbey** [comment]
Я лучше добавлю какой-то абзац сразу после карты, мол, это не только конференция и есть другие события.

**Comment by tsergeytovarov** [comment]
@pepelsbey ты не добавлял ничего? Оставляем как есть, правим как Маша предложила или просто закрываем?

**Comment by pepelsbey** [comment]
Оставляем как есть
