### ISSUE TITLE
Аутлайны кнопки обрезаются

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/2018#71]
![image](https://user-images.githubusercontent.com/105274/39971294-4bf4fe2e-5701-11e8-9431-b53d562deb6e.png)

![image](https://user-images.githubusercontent.com/105274/39971296-50079936-5701-11e8-9a6c-9d1abdb80fee.png)

**Comment by zateya** [comment]
Это из-за overflow у header. А overflow стоит из-за псевдо-элемента after (серая пиксельная линия под шапкой, шириной 100vw), который все-равно не показывается, т.к. он высотой 1 пиксель и у него bottom -1px.  Если избавиться от after, то overflow не будет нужен. Это из разряда быстрых решений, наверное.

**Comment by pepelsbey** [comment]
@tsergeytovarov ping?
