### ISSUE TITLE
При клике на кнопку плюсика не работает открытие текста о спикере

### ISSUE THREAD

**Issue by zateya** [pitercss/2018#72]
![image](https://user-images.githubusercontent.com/22032467/40420804-30a2e896-5e92-11e8-8d89-0acd06195b56.png)

и как следствие интерфейс не является доступным, открытие описания не работает с клавиатуры.

**Comment by pepelsbey** [comment]
Спасибо за репорт! У нас сначала всё правильно работало, но захотелось лучше. Чиним!

**Comment by pepelsbey** [comment]
Починили! Спасибо :)
